"""
generator/writer.py
Persists the generated schema.yml into the dbt models directory.
"""

from pathlib import Path


HEADER = """\
# ──────────────────────────────────────────────────────────────
# schema.yml  —  AUTO-GENERATED by AutoTest AI
# Do not edit by hand — re-run autotest_ai.py to regenerate.
# ──────────────────────────────────────────────────────────────

"""


def save_schema_yml(models_dir: str | Path, content: str) -> Path:
    """Write (or overwrite) schema.yml in *models_dir*."""
    out_path = Path(models_dir) / "schema.yml"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(HEADER + content, encoding="utf-8")
    return out_path
